/* ═══════════════════════════════════════════════════════
   COMPASS - ORBIT Operations Center — API Client (SDK POC)
   ═══════════════════════════════════════════════════════ */

const API = {
    baseUrl: (window.ORBIT_CONFIG && window.ORBIT_CONFIG.API_BASE_URL) || 'http://localhost:8000',

    _getHeaders() {
        return { 'Content-Type': 'application/json' };
    },

    async _fetch(method, path, body = null) {
        const opts = { method, headers: this._getHeaders() };
        if (body) opts.body = JSON.stringify(body);

        try {
            const res = await fetch(`${this.baseUrl}${path}`, opts);
            if (!res.ok) {
                const err = await res.json().catch(() => ({ detail: res.statusText }));
                throw new Error(err.detail || `Request failed: ${res.status}`);
            }
            if (res.status === 204) return null;
            return res.json();
        } catch (error) {
            console.error("API Fetch Error:", error);
            throw error;
        }
    },

    get(path)        { return this._fetch('GET', path); },
    post(path, body) { return this._fetch('POST', path, body); },
    delete(path)     { return this._fetch('DELETE', path); },

    // ── Auth ──
    login(email, password) { return Promise.resolve({ access_token: "mock", user: Auth.user }); },
    getMe()                { return Promise.resolve(Auth.user); },

    // ── AOIs ──
    async listAOIs() { 
        return [
            { id: "aoi-dublin-tiny", name: "Dublin City Center (Tiny Test Area)", area_km2: 2.5, geometry: { type: "Polygon", coordinates: [[[-6.27, 53.34], [-6.25, 53.34], [-6.25, 53.35], [-6.27, 53.35], [-6.27, 53.34]]] } },
            { id: "aoi-ireland", name: "Ireland (SDG 11.3.1 Demo)", area_km2: 70273, geometry: { type: "Polygon", coordinates: [[[-10, 51], [-5, 51], [-5, 55], [-10, 55], [-10, 51]]] } },
            { id: "aoi-kabul", name: "Kabul, Afghanistan", area_km2: 275, geometry: { type: "Polygon", coordinates: [[[68.9, 34.4], [69.3, 34.4], [69.3, 34.6], [68.9, 34.6], [68.9, 34.4]]] } }
        ]; 
    },
    
    // ── Jobs ──
    async listIndicators() {
        return this.get('/indicators');
    },

    async listJobs(params = {}) {
        try {
            const data = await this.get('/exports');
            const jobs = data.map(job => this._mapSdkJobToUiJob(job));
            return jobs.sort((a, b) => new Date(b.submitted_at) - new Date(a.submitted_at));
        } catch (e) {
            console.warn("Could not load global jobs list", e);
            return [];
        }
    },

    async getJob(id) { 
        const data = await this.get(`/exports/${id}`);
        return this._mapSdkJobToUiJob(data);
    },

    async retryJob(id) {
        const data = await this.post(`/exports/${id}/retry`);
        return this._mapSdkJobToUiJob(data);
    },

    async deleteJob(id) {
        return this.delete(`/exports/${id}`);
    },

    async getJobDownloads(fileId) { 
        if (!fileId) return [];
        const data = await this.get(`/download-links/${fileId}`);
        return data.files || [];
    },

    async createJob(data) {
        console.log("=== [API] createJob called ===");
        console.log("1. Raw UI Data:", data);

        // Map UI 'data' to SDK 'ExportRequest' payload
        const startYear = data.year_start || (data.date_range_start ? parseInt(data.date_range_start.split('-')[0]) : 2020);
        const endYear = data.year_end || (data.date_range_end ? parseInt(data.date_range_end.split('-')[0]) : 2020);

        // Get the geometry from our mocked list
        const aois = await this.listAOIs();
        const selectedAoi = aois.find(a => a.id === data.aoi_id);
        console.log("2. Selected AOI Geometry:", selectedAoi ? "Found" : "Missing");

        // Base payload
        const payload = {
            ...data, // merge all dynamic fields generated by Schema-Driven UI
            indicator_id: data.indicator_id,
            year_start: startYear,
            year_end: endYear,
            aoi_geojson: selectedAoi ? selectedAoi.geometry : undefined
        };

        console.log("3. Final SDK Payload to send:", payload);

        const res = await this.post('/exports', payload);
        console.log("4. Response from Backend:", res);
        
        // Save job ID to local storage so listJobs can find it
        const savedIds = JSON.parse(localStorage.getItem('orbit_jobs') || '[]');
        savedIds.push(res.job_id);
        localStorage.setItem('orbit_jobs', JSON.stringify(savedIds));

        return this._mapSdkJobToUiJob(res);
    },

    _mapSdkJobToUiJob(sdkData) {
        // Map the SDK's ExportStatusResponse to the UI's JobResponse format
        const stateMap = {
            "queued": "PENDING",
            "running": "PROCESSING",
            "completed": "COMPLETED",
            "failed": "FAILED",
            "cancelled": "CANCELLED"
        };
        return {
            id: sdkData.job_id,
            fileId: sdkData.fileId,
            indicator_id: sdkData.request ? sdkData.request.indicator_id : "11.3.1",
            state: stateMap[sdkData.status] || "PENDING",
            submitted_at: sdkData.created_at,
            aoi_name: sdkData.result?.country || sdkData.request?.country || "Custom AOI",
            aoi_id: sdkData.result?.country || sdkData.request?.country || "custom",
            date_range_start: sdkData.result?.year_start,
            date_range_end: sdkData.result?.year_end,
            results_data: sdkData.result ? {
                "population_change_pct": "Completed", 
                "land_consumption_pct": "Check Downloads"
            } : null,
            result: sdkData.result || null,
            layers: (sdkData.result?.layers || []).map(layer => {
                // If the layer is already marked as a COG URL, just prepend the base URL
                if (layer.is_cog) {
                    layer.tile_url = `${this.baseUrl}${layer.tile_url}`;
                } 
                // Legacy fallback: if it's an old EE MapID but we have the GCS filename, rewrite it dynamically!
                else if (sdkData.result?.geotiff_file_name_prefix) {
                    const bucket = "unops"; // Default bucket for old jobs
                    const prefix = sdkData.result.geotiff_file_name_prefix;
                    layer.tile_url = `${this.baseUrl}/cog/tiles/WebMercatorQuad/{z}/{x}/{y}?url=gs://${bucket}/${prefix}.tif&bidx=1&nodata=0&colormap=%7B"1":"%23FF5722FF"%7D`;
                }
                return layer;
            })
        };
    },

    approveJob(id)   { return Promise.resolve(); }, // Auto-approved in POC
    async cancelJob(id) { 
        const data = await this.post(`/exports/${id}/cancel`, {});
        return this._mapSdkJobToUiJob(data);
    },
    deleteJob(id) { return this.del(`/exports/${id}`); },

    // ── Layers ──
    getUrbanExpansion(aoiId) { return Promise.resolve({}); }
};
